# Generated by Django 2.1.7 on 2020-07-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='Party',
            new_name='party',
        ),
    ]
