# Generated by Django 2.1.7 on 2020-07-08 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(default='defo', upload_to='results/')),
                ('second_image', models.ImageField(default='defo', upload_to='results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
